# Generated by Django 5.1 on 2024-08-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rentalpayments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalpayments',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='rentalpayments',
            name='status',
            field=models.CharField(choices=[('unpaid', 'UNPAID')], default='unpaid', max_length=6),
        ),
        migrations.AlterField(
            model_name='property',
            name='rental_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
