# Generated by Django 5.1 on 2024-08-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_rentalpayments_is_paid_rentalpayments_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpayments',
            name='status',
            field=models.CharField(choices=[('unpaid', 'UNPAID'), ('unpaid', 'PAID')], default='unpaid', max_length=6),
        ),
    ]
