# Generated by Django 5.1 on 2024-08-30 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_tenant_occupied_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='unit',
        ),
        migrations.AddField(
            model_name='tenant',
            name='occupied_section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.property'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
