# Generated by Django 5.1 on 2024-08-31 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_tenant_unit_tenant_occupied_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpayments',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalpayments',
            name='status',
            field=models.CharField(choices=[('unpaid', 'UnPaid'), ('paid', 'Paid')], default='unpaid', max_length=6),
        ),
        migrations.AlterField(
            model_name='rentalpayments',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='management.tenant'),
        ),
    ]
