# Generated by Django 5.1 on 2024-08-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_rentalpayments_paid_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalpayments',
            old_name='paid_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='rentalpayments',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=6),
        ),
    ]
