# Generated by Django 5.1 on 2024-09-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_rename_paid_date_rentalpayments_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentalpayments',
            unique_together={('tenant', 'date')},
        ),
    ]
