# Generated by Django 5.1 on 2024-09-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_rentalpayments_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentalpayments',
            unique_together=set(),
        ),
    ]
