# Generated by Django 5.1 on 2024-09-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_rentalpayments_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalpayments',
            old_name='date',
            new_name='paid_date',
        ),
        migrations.AlterUniqueTogether(
            name='rentalpayments',
            unique_together={('tenant', 'paid_date')},
        ),
    ]
