# Generated by Django 5.1 on 2024-09-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_rename_date_rentalpayments_paid_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalpayments',
            old_name='paid_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='rentalpayments',
            unique_together={('tenant', 'date')},
        ),
    ]
