# Generated by Django 5.1 on 2024-09-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_rename_paid_date_rentalpayments_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpayments',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
