# Generated by Django 5.1 on 2024-09-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_rentalpayments_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
